/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LevelProgress = IDL.Record({
  'completed' : IDL.Bool,
  'bestScore' : IDL.Nat,
});
export const PlayerProfile = IDL.Record({
  'username' : IDL.Text,
  'totalScore' : IDL.Nat,
  'currentLevel' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLevelConfig' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'targetScore' : IDL.Nat, 'gridSize' : IDL.Nat })],
      ['query'],
    ),
  'getLevelProgress' : IDL.Func([IDL.Nat], [LevelProgress], ['query']),
  'getPlayerProfile' : IDL.Func([], [PlayerProfile], ['query']),
  'getTopPlayers' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetAllPlayerData' : IDL.Func([], [], []),
  'saveLevelProgress' : IDL.Func([IDL.Nat, LevelProgress], [], []),
  'savePlayerProfile' : IDL.Func([PlayerProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LevelProgress = IDL.Record({
    'completed' : IDL.Bool,
    'bestScore' : IDL.Nat,
  });
  const PlayerProfile = IDL.Record({
    'username' : IDL.Text,
    'totalScore' : IDL.Nat,
    'currentLevel' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLevelConfig' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'targetScore' : IDL.Nat, 'gridSize' : IDL.Nat })],
        ['query'],
      ),
    'getLevelProgress' : IDL.Func([IDL.Nat], [LevelProgress], ['query']),
    'getPlayerProfile' : IDL.Func([], [PlayerProfile], ['query']),
    'getTopPlayers' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetAllPlayerData' : IDL.Func([], [], []),
    'saveLevelProgress' : IDL.Func([IDL.Nat, LevelProgress], [], []),
    'savePlayerProfile' : IDL.Func([PlayerProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };